//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakkaat
    {
        public Asiakkaat()
        {
            this.Tilaus = new HashSet<Tilaus>();
        }
    
        public int asiakasId { get; set; }
        public string yhteysHenkilö { get; set; }
        public string yritysNimi { get; set; }
        public Nullable<int> puhelin { get; set; }
        public string sähköposti { get; set; }
    
        public virtual ICollection<Tilaus> Tilaus { get; set; }
    }
}
