//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestifkpkEntities : DbContext
    {
        public TestifkpkEntities()
            : base("name=TestifkpkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asiakkaat> Asiakkaat { get; set; }
        public DbSet<Henkilöstö> Henkilöstö { get; set; }
        public DbSet<Logins> Logins { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tilaus> Tilaus { get; set; }
        public DbSet<Tilausrivi> Tilausrivi { get; set; }
        public DbSet<Tuotteet> Tuotteet { get; set; }
    }
}
