//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilaus
    {
        public Tilaus()
        {
            this.Tilausrivi = new HashSet<Tilausrivi>();
        }
    
        public int tilausId { get; set; }
        public System.DateTime tilausPvm { get; set; }
        public int asiakasId { get; set; }
    
        public virtual Asiakkaat Asiakkaat { get; set; }
        public virtual ICollection<Tilausrivi> Tilausrivi { get; set; }
    }
}
