//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naytto1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuotteet
    {
        public Tuotteet()
        {
            this.Tilausrivi = new HashSet<Tilausrivi>();
        }
    
        public int tuoteId { get; set; }
        public string Kuvaus { get; set; }
        public string TuoteMerkki { get; set; }
        public string TuoteMalli { get; set; }
        public int Määrä { get; set; }
        public string Sarjanumero { get; set; }
        public int HenkilöId { get; set; }
    
        public virtual ICollection<Tilausrivi> Tilausrivi { get; set; }
    }
}
